import gemini from "../lib/gemini.js";

export default {
    name: "coding",
    description: "AI Coding Assistant with Auto-Copy Buttons",
    command: ["code", "coding", "prog", "dev"],
    tags: ["ai", "tools"],
    run: async (context) => {
        const { m, text, sock } = context;
        
        if (!text) return m.reply("Mana instruksinya wir? Mau bikin kode apa?");

        await m.react("⏳");

        // System prompt untuk memastikan output selalu ada markdown code block
        const messages = [
            { 
                role: "system", 
                content: "You are an expert universal coding assistant. You can write code in any programming language. " +
                         "Always wrap your code snippets in markdown code blocks (e.g., ```javascript ... ```). " +
                         "Keep explanations concise but clear. " +
                         "If the user asks for code, prioritizing giving the code directly."
            },
            { role: "user", content: text }
        ];

        try {
            // Request ke model gemini-3-pro-preview
            const response = await gemini(messages, null, "gemini-3-pro-preview");

            // Regex untuk menangkap konten di dalam ```kode```
            // Menangkap grup 1: konten kode (mengabaikan bahasa yang ditulis setelah backticks)
            const codeBlockRegex = /```(?:[\w\+\-\.]+)?\s*([\s\S]*?)```/g;
            
            const buttons = [];
            let match;
            let count = 1;

            // Loop untuk mencari semua blok kode dalam response
            while ((match = codeBlockRegex.exec(response)) !== null) {
                const codeContent = match[1].trim(); // Ambil kodenya saja, hapus spasi awal/akhir
                
                if (codeContent) {
                    buttons.push({
                        name: "cta_copy",
                        buttonParamsJson: JSON.stringify({
                            display_text: `Copy Code ${count}`,
                            copy_code: codeContent
                        })
                    });
                    count++;
                }
            }

            // Jika ada kode yang terdeteksi, kirim sebagai Interactive Message dengan tombol Copy
            if (buttons.length > 0) {
                await sock.sendInteractiveMessage(m.chat, {
                    text: response,
                    footer: "🤖 Generated by Gemini 3 Pro",
                    interactiveButtons: buttons
                }, { quoted: m });
            } else {
                // Fallback jika tidak ada blok kode (misal cuma penjelasan teori)
                await m.reply(response);
            }

            await m.react("✅");

        } catch (e) {
            console.error(e);
            await m.reply("Waduh, error nih banh saat generate kodenya. Coba lagi nanti ya.");
            await m.react("❌");
        }
    }
};
